### ISSUE TITLE
Value not changing if used setValue(newvalue)

### ISSUE THREAD

**Issue by kosheeta** [pie6k/use-state-shared#2]
Hello!

In one component, I used this code:
```
const [urlParams, setUrlParams] = useUrlParamsStore()

setUrlParams(new URLSearchParams(document.location.search))

console.log(new URLSearchParams(document.location.search))  // out: {...} (data)

console.log(urlParams) // out: {} (blank)
```

There is same with sessionId - string. But with other variable (json object) all well.

Where is the error?

**Comment by kosheeta** [comment]
If I try to access value in other component, the value is well.

(Sorry for my bad English)

**Comment by pie6k** [comment]
Could you provide more code related to your issue (creating the store, components using it, what is URLSearchParams in your case)?
